version: '3.7'
services:
  app:
    container_name: todo-backend
    build: .
    restart: always
    build: .
    env_file:
      - .env.prod
    ports:
      - '3001:3001'
  mongo:
    image: mongo:4.4.4
    volumes: 
      - 'mongodb:/data/db'

volumes: 
  mongodb:
