version: '3.7'
services:
  app:
    container_name: todo-backend
    restart: always
    build: .
    env_file:
      - .env.prod
    ports:
      - '3001:3001'
  mongo:
    image: mongo
  node:
    image: node
